### ISSUE TITLE
Guide: Setup CI pipeline with Google Java Format for Spring Boot Apps

### ISSUE THREAD

**Issue by BrightProgrammer7** [BrightProgrammer7/FORMAT-JAVA-CI#5]
### Setup continuous integration pipeline with Google Java Format action

**1. CI: create format-check job in your continuous integration pipeline**
> Google Java Format Action can automatically check the formatting of your Java files without committing anything and using [Google Java Style guidelines](https://google.github.io/styleguide/javaguide.html) and it downloads the latest release of the [Google Java Format](https://github.com/google/google-java-format) program.
> <img width="1440" alt="Screenshot 2024-08-21 at 17 40 08" src="https://github.com/user-attachments/assets/86aa181d-4803-456e-9789-dd6a168ad12d">
> This action will check if the formatting is correct without pushing anything.

```
name: Format 

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
``` 

**2. Style: Format code with Google Java Style guideline**
<img width="1440" alt="Screenshot 2024-08-21 at 17 42 44" src="https://github.com/user-attachments/assets/b1dd50f2-ab4c-4695-ae08-b66d197eb937">

**3. Test: Check your CI workflow in Github Actions**
> Successfully format-check job have passed in CI Pipeline using Google Java Format Action
> <img width="1440" alt="Screenshot 2024-08-21 at 17 45 01" src="https://github.com/user-attachments/assets/3d230e3e-22fb-4b2c-b222-9bcbce2f7a93">
> <img width="1440" alt="Screenshot 2024-08-21 at 17 45 24" src="https://github.com/user-attachments/assets/95baba73-bd4b-45f2-b805-713585d42200">

**4. Feat: Accept the opened PR and merge to your base branch**
> <img width="1440" alt="Screenshot 2024-08-21 at 18 18 22" src="https://github.com/user-attachments/assets/38a7c075-c4d7-4c1e-b21f-16de52537231">
> <img width="1440" alt="Screenshot 2024-08-21 at 18 18 38" src="https://github.com/user-attachments/assets/6eacdb07-739e-4a0f-9eaa-3f88bb33cffb">
